### PR TITLE
Change a bit of requirements.txt

### LINKED ISSUE #60: Request: Update requirements.txt with most required modules with OS locks
In gist:
The title

Reason:
It is hard, as of now, to start developing on a barebones Onyx(previously Txt2) without module errors on Darwin and Tux(Darwin is the architecture name for Macs and Tux[ik it's not official but it seems better that way] as Linux). Since Onyx's primary devsystem is on Windows, it is a bit hard to just kickstart devwork on the other systems. Hence what I am asking is to test on any POSIX-COMPLIANT systems for modules and lock the ones needed only for Windows, plus include the modules previously marked as not installed on the pip directories.

How to achieve:
Simple. Head onto Gitpod or hit this link: https://gitpod.io/#https://github.com/not-nef/onyx and install all the modules. Then run main.py, expect an error, install the module+append the name to requirements.txt and keep repeating until all modules work and Python throws a nodisplay-ish error.

Or just give me a week's time and get the PR on Sunday. How's that sound?

Liberations:
From a lot of errors and failures on Darwin and Tux

Complications:
More logs to manage on the console(who cares?).

Finally:
Up to you @not-nef. I spoke my part. Now the ball is in your court.

### PR DESCRIPTION
**Pull request by im-coder-lg**
Surprisingly, the change was a bit low than expected. Great job on that!

Resolves #60 

And yes, 7e2a317 is signed and it speaks for itself.

### CODE REVIEW

**Comment by sumeshir26** [comment]
The requests module is nessary for checking for updaes. otherwise, lgtm

**Comment by im-coder-lg** [comment]
Hmm, it seems to be installed by default on most Linux distros with Python. The requests module is in the system software repositories, ie. if I were you, I would _not_ use pip for this, I will use the `apt`(Debian), `dnf`(Fedora, RHEL, CentOS) or `pacman`(ArchLinux-based) package manager(or summat similar) to install requests. On the other hand, using Python on macOS is done best with Anaconda3 since it gives you most of the required modules like Tk8.6, plus requests(every data science toolkit should have that) so worry less, it would be counterintuitive adding it here.

**Comment by im-coder-lg** [comment]
And it is mostly installed with Python on Windows, else you can't just kickstart a JSON request, right?

**Comment by not-nef** [comment]
it does NOT come with python. (atleast on windows). add it back or no merge.

**Review by not-nef — CHANGES_REQUESTED** [review]
it does NOT come with python. (atleast on windows). add it back or no merge.

**Comment by im-coder-lg** [comment]
I'll try to do it today, I got school. It's weird that requests doesn't come pre-installed. But adding it would mean that I will add a lock for Windows and possibly macOS. Linux jas the module in the software repositories, ie. the Software Store.

**Comment by im-coder-lg** [comment]
Okay, I will add it and.lock it only for Windows and macOS. You will have to use a package manager to get requests on Linux(third time I told).

**Review by sumeshir26 — APPROVED** [review]

**Review by not-nef — APPROVED** [review]

**Comment by rdbende** [comment]
The `requests` module was NOT pre-installed on my Debian system, I installed it with `pip`. I would add it back to requirements.

**Comment by not-nef** [comment]
he did

**Comment by rdbende** [comment]
But only for mac and Windows. It's disabled on Linux

**Comment by not-nef** [comment]
but why not install it via pip? do you really want linux users to run an extra command when installing the onyx dependencies?

**Comment by rdbende** [comment]
But why use apt or nala, if I use pip to install other Python modules anyway?

**Comment by im-coder-lg** [comment]
Well, it makes the module global. Most websites that have guides on getting modules like this on Linux use apt to install it. It seems to be stable too.

**Comment by im-coder-lg** [comment]
Plus, it kinda doesn't work on some other systems, so an apt install would work in that case.

**Comment by rdbende** [comment]
I'll leave it up to you. I would never use the system's package manager, if the module has complete wheels on Pypi, but I'm bot a contributor of onyx, so it's not my task to decide.

**Pull request merged**
